server:
  port: 8191
  servlet:
    context-path: /task-manager

spring:
  application:
    name: task-manager
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/task_manager
    username: root
    password: root
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
  mysql:
    console:
      enabled: true
      settings:
        web-allow-others: false

jwt:
  secret: aKaztBKD6z66JfEuXzGvPAhuoKHXOhsRdkNKoA3wbPeRCF8Hoy
  lifetime: 3600000