version: '3'

services:
  mysql:
    image: mysql:8.2-oraclelinux8
    domainname: mysql
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=task_manager
    healthcheck:
      test: [ "CMD-SHELL", "nc -z 127.0.0.1 3306 || exit 1" ]
      interval: 1m30s
      timeout: 60s
      retries: 6

  flyway:
    container_name: task-manager-flyway
    image: boxfuse/flyway
    command: -url=jdbc:mysql://mysql:3306/task_manager?verifyServerCertificate=false -user=root -password=root -connectRetries=30 migrate
    volumes:
      - ./db/migration:/flyway/sql
    depends_on:
      - mysql
